CREATE TABLE ACTOR (
  ACTOR_ID INTEGER PRIMARY KEY,
  FIRST_NAME VARCHAR(45) NOT NULL,
  LAST_NAME VARCHAR(45) NOT NULL
);

CREATE TABLE AUDIT_LOG (
  AUDIT_LOG_ID INTEGER PRIMARY KEY,
  MESSAGE VARCHAR(255) NOT NULL
);
